package parser

import (
	"testing"

	"github.com/indeedhat/monkey-lang/ast"
	"github.com/indeedhat/monkey-lang/lexer"
	"github.com/stretchr/testify/require"
)

// parseProgram invokes the lexer/parser and returns the resulting ast
// basic errors checking will be handled along the way
func parseProgram(t *testing.T, input string) *ast.Program {
	lex := lexer.New(input)
	parser := New(lex)

	program := parser.ParseProgram()
	checkParserErrors(t, parser)

	require.NotNil(t, program, "program")

	return program
}

// checkParserErrors checks for and displays any errors generated by the parser
func checkParserErrors(t *testing.T, p *Parser) {
	errors := p.Errors()
	if len(errors) == 0 {
		return
	}

	t.Errorf("Parser produced %d error(s):", len(errors))

	for _, err := range errors {
		t.Errorf("Parser Error: %s", err.Error())
	}

	t.FailNow()
}
